# Generated by Django 5.2.16 on 2026-09-03 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_id', models.CharField(max_length=64)),
                ('location', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=64)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('start_ts', models.DateTimeField()),
                ('end_ts', models.DateTimeField(blank=True, null=True)),
                ('modality', models.CharField(choices=[('rgb', 'RGB'), ('thermal', 'Thermal')], default='rgb', max_length=16)),
            ],
            options={
                'indexes': [models.Index(fields=['camera_id', 'start_ts'], name='core_deploy_camera__dab4e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024, unique=True)),
                ('source', models.CharField(choices=[('ingest', 'Ingest'), ('video_frame', 'Video frame')], default='ingest', max_length=16)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('is_blank', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.deployment')),
            ],
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('person', 'Person'), ('vehicle', 'Vehicle'), ('animal', 'Animal')], max_length=16)),
                ('confidence', models.FloatField()),
                ('bbox_x1', models.FloatField()),
                ('bbox_y1', models.FloatField()),
                ('bbox_x2', models.FloatField()),
                ('bbox_y2', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='core.image')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024, unique=True)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=16)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('error', models.TextField(blank=True, default='')),
                ('start_offset_ts', models.FloatField(default=0)),
                ('fps', models.FloatField(blank=True, null=True)),
                ('gop_size', models.IntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.deployment')),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('speciesnet', 'SpeciesNet'), ('human', 'Human')], default='speciesnet', max_length=16)),
                ('category', models.CharField(max_length=255)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('top_k', models.JSONField(default=list)),
                ('model_version', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annotator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('detection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='core.detection')),
            ],
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['source', 'status'], name='core_image_source_a04c3e_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['is_blank'], name='core_image_is_blan_88e569_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['deployment', 'captured_at'], name='core_image_deploym_1ebb6f_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['confidence'], name='core_detect_confide_f41ae9_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['category'], name='core_detect_categor_d28f77_idx'),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['status'], name='core_detect_status_86c5bc_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['deployment', 'start_offset_ts'], name='core_media_deploym_d25e6e_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['status'], name='core_media_status_7b9bd7_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['uploaded_at'], name='core_media_uploade_a09e62_idx'),
        ),
        migrations.AddIndex(
            model_name='speciesclassification',
            index=models.Index(fields=['detection', 'source'], name='core_specie_detecti_2d4d41_idx'),
        ),
    ]
