# Generated by Django 5.2.16 on 2026-09-03 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_frame', models.IntegerField()),
                ('end_frame', models.IntegerField()),
                ('start_ts', models.FloatField()),
                ('end_ts', models.FloatField()),
                ('hits', models.IntegerField()),
                ('rep_ts', models.FloatField(blank=True, null=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='core.media')),
                ('rep_detection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.detection')),
            ],
        ),
        migrations.CreateModel(
            name='MotionSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.FloatField()),
                ('displacement_bl_per_s', models.FloatField()),
                ('deformation_score', models.FloatField()),
                ('confidence', models.FloatField()),
                ('bbox_x1', models.FloatField()),
                ('bbox_y1', models.FloatField()),
                ('bbox_x2', models.FloatField()),
                ('bbox_y2', models.FloatField()),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='video.track')),
            ],
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['media', 'start_ts'], name='video_track_media_i_3fb7ab_idx'),
        ),
        migrations.AddIndex(
            model_name='motionsignal',
            index=models.Index(fields=['track', 'ts'], name='video_motio_track_i_6168f6_idx'),
        ),
    ]
