# Generated by Django 5.2.16 on 2026-07-22 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=1024, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('is_blank', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['status'], name='detections__status_7bff93_idx'), models.Index(fields=['is_blank'], name='detections__is_blan_2eb8aa_idx')],
            },
        ),
        migrations.CreateModel(
            name='Detection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('person', 'Person'), ('vehicle', 'Vehicle'), ('animal', 'Animal')], max_length=16)),
                ('confidence', models.FloatField()),
                ('bbox_x1', models.FloatField()),
                ('bbox_y1', models.FloatField()),
                ('bbox_x2', models.FloatField()),
                ('bbox_y2', models.FloatField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detections', to='detections.image')),
            ],
            options={
                'indexes': [models.Index(fields=['confidence'], name='detections__confide_b1f5f2_idx'), models.Index(fields=['category'], name='detections__categor_2113e4_idx')],
            },
        ),
    ]
