# Generated by Django 5.2.16 on 2026-07-27 03:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_site', models.CharField(blank=True, default='', max_length=255)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('image_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('confidence', models.FloatField()),
                ('detection_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpeciesClassification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('speciesnet', 'SpeciesNet'), ('human', 'Human')], default='speciesnet', max_length=16)),
                ('category', models.CharField(max_length=255)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('top_k', models.JSONField(default=list)),
                ('model_version', models.CharField(blank=True, default='', max_length=64)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='detection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='image',
            name='camera_site',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='image',
            name='captured_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='detection',
            index=models.Index(fields=['status'], name='detections__status_4e211d_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['camera_site', 'start_time'], name='detections__camera__1a9d46_idx'),
        ),
        migrations.AddField(
            model_name='image',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='detections.event'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['camera_site', 'captured_at'], name='detections__camera__db6d3e_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['event'], name='detections__event_i_2a6cb5_idx'),
        ),
        migrations.AddField(
            model_name='eventspecies',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='detections.event'),
        ),
        migrations.AddField(
            model_name='eventspecies',
            name='representative_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='detections.image'),
        ),
        migrations.AddField(
            model_name='speciesclassification',
            name='annotator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='speciesclassification',
            name='detection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='detections.detection'),
        ),
        migrations.AlterUniqueTogether(
            name='eventspecies',
            unique_together={('event', 'category')},
        ),
        migrations.AddIndex(
            model_name='speciesclassification',
            index=models.Index(fields=['detection', 'source'], name='detections__detecti_1e665c_idx'),
        ),
    ]
