# Generated by Django 5.2.16 on 2026-08-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0002_event_eventspecies_speciesclassification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
    ]
